main: fr.wixonic.walkerschatevent.Main
api-version: "1.20"
version: 1.0.0

author: Wixonic
name: W47K3R5 Chat Events
description: A custom Chat Event for Alan Walker's Minecraft server
website: "https://github.com/Wixonic/WalkersChatEvents"