main: fr.wixonic.walkerschatevent.Main
api-version: 1.20
version: 1.1.3

author: Wixonic
name: W47K3R5-Chat-Event
description: A custom chat event plugin for Alan Walker's Minecraft server
website: https://github.com/Wixonic/WalkersChatEvent

commands:
    chatevent:
        aliases: chev
        description: Starts a chat event
        usage: /<command>
        permission: chatevent.create
        permission-message: You do not have permission to use this command.

permissions:
    chatevent.create:
        description: Allows to create a chat event
        default: op